language: node_js
node_js:
  - "0.10.25"
before_script:
  - cp config.coffee.test config.coffee
  - psql -c 'create database ioweyou_test;' -U postgres
script:
  - "grunt mochaTest"
services:
  - redis-server
notifications:
  webhooks: https://kodiksy.slack.com/services/hooks/travis?token=VlTr1mcY6EqJJkOIyTXWjlr9
